// Auto-generated by tools/generate_structs.py from the pinned packet-observation payload layouts.
// Bucket: WorldClientbound. Do not edit by hand; re-run the generator.
#pragma once

#include <cstdint>

#pragma pack(push, 1)

namespace bahamut::opcodes::world
{
namespace clientbound
{

// 0x00c9 (opcode 201) - sub_size=584B body=560B samples=5
struct PartyChatMessageBody
{
    uint8_t  _const0;     // body[+0] = 0x0a
    uint8_t  _pad1[7];    // body[+1..+7] zero
    uint8_t  field2;      // body[+8] u8 (2 distinct)
    uint8_t  _const3;     // body[+9] = 0x3f
    uint8_t  _pad4[34];   // body[+10..+43] zero
    uint8_t  field5[3];   // body[+44..+46] 3B (3 distinct)
    uint8_t  _pad6[7];    // body[+47..+53] zero
    uint16_t field7;      // body[+54..+55] u16 (2 distinct)
    uint8_t  _pad8[13];   // body[+56..+68] zero
    uint16_t field9;      // body[+69..+70] u16 (2 distinct)
    uint8_t  _pad10[489]; // body[+71..+559] zero
};

static_assert(sizeof(PartyChatMessageBody) == 560, "PartyChatMessageBody size mismatch");

} // namespace clientbound
} // namespace bahamut::opcodes::world

#pragma pack(pop)
