// Auto-generated by tools/generate_structs.py from the pinned packet-observation payload layouts.
// Bucket: WorldServerbound. Do not edit by hand; re-run the generator.
#pragma once

#include <cstdint>

#pragma pack(push, 1)

namespace bahamut::opcodes::world
{
namespace serverbound
{

// 0x00c9 (opcode 201) - sub_size=552B body=528B samples=6
struct PartyChatMessageBody
{
    uint8_t  _const0;    // body[+0] = 0x0a
    uint8_t  _pad1[7];   // body[+1..+7] zero
    uint8_t  _const2;    // body[+8] = 0xd7
    uint8_t  _const3;    // body[+9] = 0x3f
    uint8_t  _pad4[2];   // body[+10..+11] zero
    uint8_t  field5[3];  // body[+12..+14] 3B (2 distinct)
    uint8_t  _pad6[38];  // body[+15..+52] zero
    uint16_t field7;     // body[+53..+54] u16 (2 distinct)
    uint8_t  _pad8[469]; // body[+55..+523] zero
    uint32_t field9;     // body[+524..+527] u32 (2 distinct)
};

static_assert(sizeof(PartyChatMessageBody) == 528, "PartyChatMessageBody size mismatch");

} // namespace serverbound
} // namespace bahamut::opcodes::world

#pragma pack(pop)
