// Auto-generated by tools/generate_structs.py from the pinned packet-observation payload layouts.
// Bucket: MapServerbound. Do not edit by hand; re-run the generator.
#pragma once

#include <cstdint>

#pragma pack(push, 1)

namespace bahamut::opcodes::map
{
namespace serverbound
{

// 0x0001 (opcode 1) - sub_size=56B body=32B samples=60
struct PingBody
{
    uint16_t field0;    // body[+0..+1] u16 (54 distinct)
    uint8_t  _const1;   // body[+2] = 0xe0
    uint8_t  _const2;   // body[+3] = 0x50
    uint8_t  _pad3[4];  // body[+4..+7] zero
    uint8_t  field4[3]; // body[+8..+10] 3B (57 distinct)
    uint8_t  _const5;   // body[+11] = 0x0a
    uint8_t  _pad6[20]; // body[+12..+31] zero
};

static_assert(sizeof(PingBody) == 32, "PingBody size mismatch");

// 0x0003 (opcode 3) - sub_size=576B body=552B samples=2
struct ChatMessageBody
{
    uint8_t  field0;      // body[+0] u8 (2 distinct)
    uint8_t  _const1;     // body[+1] = 0xf5
    uint8_t  _const2;     // body[+2] = 0xe0
    uint8_t  _const3;     // body[+3] = 0x50
    uint8_t  _pad4[12];   // body[+4..+15] zero
    uint8_t  _const5;     // body[+16] = 0x80
    uint8_t  _const6;     // body[+17] = 0xf3
    uint8_t  _const7;     // body[+18] = 0xe3
    uint8_t  _const8;     // body[+19] = 0x44
    uint8_t  _const9;     // body[+20] = 0xfa
    uint8_t  _const10;    // body[+21] = 0x78
    uint8_t  _const11;    // body[+22] = 0x15
    uint8_t  _const12;    // body[+23] = 0x43
    uint8_t  _const13;    // body[+24] = 0xcb
    uint8_t  _pad14;      // body[+25] zero
    uint8_t  _const15;    // body[+26] = 0xd8
    uint8_t  _const16;    // body[+27] = 0x44
    uint8_t  _const17;    // body[+28] = 0x17
    uint8_t  _const18;    // body[+29] = 0xa8
    uint8_t  _const19;    // body[+30] = 0x16
    uint8_t  _const20;    // body[+31] = 0xc0
    uint8_t  field21;     // body[+32] u8 (2 distinct)
    uint8_t  _pad22[515]; // body[+33..+547] zero
    uint8_t  _const23;    // body[+548] = 0xd0
    uint16_t field24;     // body[+549..+550] u16 (2 distinct)
    uint8_t  _const25;    // body[+551] = 0x37
};

static_assert(sizeof(ChatMessageBody) == 552, "ChatMessageBody size mismatch");

// 0x0007 (opcode 7) - sub_size=40B body=16B samples=8
struct ZoneInCompleteBody
{
    uint8_t field0[3];  // body[+0..+2] 3B (8 distinct)
    uint8_t _const1;    // body[+3] = 0x50
    uint8_t _pad2[4];   // body[+4..+7] zero
    uint8_t field3[3];  // body[+8..+10] 3B (8 distinct)
    uint8_t _const4;    // body[+11] = 0x50
    uint8_t _const5[4]; // body[+12..+15] each byte = 0xff
};

static_assert(sizeof(ZoneInCompleteBody) == 16, "ZoneInCompleteBody size mismatch");

// 0x00ca (opcode 202) - sub_size=64B body=40B samples=60
struct UpdatePlayerPositionBody
{
    uint16_t field0;     // body[+0..+1] u16 (23 distinct)
    uint8_t  _const1;    // body[+2] = 0xe0
    uint8_t  _const2;    // body[+3] = 0x50
    uint8_t  _pad3[4];   // body[+4..+7] zero
    uint16_t field4;     // body[+8..+9] u16 (23 distinct)
    uint8_t  _const5;    // body[+10] = 0xe0
    uint8_t  _const6;    // body[+11] = 0x50
    uint8_t  _pad7[4];   // body[+12..+15] zero
    float    field8[4];  // body[+16..+31] 4x f32 (10 distinct)
    uint8_t  _pad9[2];   // body[+32..+33] zero
    uint8_t  _const10;   // body[+34] = 0x18
    uint8_t  _pad11;     // body[+35] zero
    uint8_t  field12[3]; // body[+36..+38] 3B (2 distinct)
    uint8_t  _pad13;     // body[+39] zero
};

static_assert(sizeof(UpdatePlayerPositionBody) == 40, "UpdatePlayerPositionBody size mismatch");

// 0x00cc (opcode 204) - sub_size=40B body=16B samples=42
struct LockTargetBody
{
    uint8_t  field0[3]; // body[+0..+2] 3B (39 distinct)
    uint8_t  _const1;   // body[+3] = 0x50
    uint8_t  _pad2[4];  // body[+4..+7] zero
    uint64_t field3;    // body[+8..+15] u64 (16 distinct)
};

static_assert(sizeof(LockTargetBody) == 16, "LockTargetBody size mismatch");

// 0x00cd (opcode 205) - sub_size=40B body=16B samples=58
struct SetTargetBody
{
    uint8_t  field0[3]; // body[+0..+2] 3B (43 distinct)
    uint8_t  _const1;   // body[+3] = 0x50
    uint8_t  _pad2[4];  // body[+4..+7] zero
    uint64_t field3;    // body[+8..+15] u64 (19 distinct)
};

static_assert(sizeof(SetTargetBody) == 16, "SetTargetBody size mismatch");

// 0x00ce (opcode 206) - sub_size=72B body=48B samples=2
struct _0x00CEBody
{
    uint8_t  field0;     // body[+0] u8 (2 distinct)
    uint8_t  _const1;    // body[+1] = 0x60
    uint8_t  _const2;    // body[+2] = 0xe1
    uint8_t  _const3;    // body[+3] = 0x50
    uint8_t  _pad4[4];   // body[+4..+7] zero
    uint8_t  field5;     // body[+8] u8 (2 distinct)
    uint8_t  _pad6[3];   // body[+9..+11] zero
    uint8_t  _const7;    // body[+12] = 0x63
    uint8_t  _const8;    // body[+13] = 0x6f
    uint8_t  _const9;    // body[+14] = 0x6d
    uint8_t  _const10;   // body[+15] = 0x30
    uint8_t  _const11;   // body[+16] = 0x67
    uint8_t  _const12;   // body[+17] = 0x31
    uint8_t  _const13;   // body[+18] = 0x30
    uint8_t  _const14;   // body[+19] = 0x35
    uint8_t  _pad15[24]; // body[+20..+43] zero
    uint32_t field16;    // body[+44..+47] u32 (2 distinct)
};

static_assert(sizeof(_0x00CEBody) == 48, "_0x00CEBody size mismatch");

// 0x012d (opcode 301) - sub_size=216B body=192B samples=60
struct EventStartBody
{
    uint8_t  field0[3];   // body[+0..+2] 3B (52 distinct)
    uint8_t  _const1;     // body[+3] = 0x50
    uint8_t  _pad2[4];    // body[+4..+7] zero
    uint8_t  _const3;     // body[+8] = 0x41
    uint8_t  _const4;     // body[+9] = 0x29
    uint8_t  _const5;     // body[+10] = 0x9b
    uint8_t  _const6;     // body[+11] = 0x02
    uint32_t field7;      // body[+12..+15] u32 (26 distinct)
    uint8_t  _pad8[2];    // body[+16..+17] zero
    uint8_t  field9[7];   // body[+18..+24] 7B (4 distinct)
    uint8_t  _pad10[5];   // body[+25..+29] zero
    uint8_t  field11[60]; // body[+30..+89] 60B (2 distinct)
    uint8_t  _pad12[8];   // body[+90..+97] zero
    uint8_t  field13;     // body[+98] u8 (2 distinct)
    uint8_t  _pad14[86];  // body[+99..+184] zero
    uint8_t  field15[7];  // body[+185..+191] 7B (2 distinct)
};

static_assert(sizeof(EventStartBody) == 192, "EventStartBody size mismatch");

// 0x012e (opcode 302) - sub_size=120B body=96B samples=60
struct EventUpdateBody
{
    uint8_t  field0[3];   // body[+0..+2] 3B (55 distinct)
    uint8_t  _const1;     // body[+3] = 0x50
    uint8_t  _pad2[4];    // body[+4..+7] zero
    uint8_t  _const3;     // body[+8] = 0x41
    uint8_t  _const4;     // body[+9] = 0x29
    uint8_t  _const5;     // body[+10] = 0x9b
    uint8_t  _const6;     // body[+11] = 0x02
    uint8_t  _pad7[2];    // body[+12..+13] zero
    uint16_t field8;      // body[+14..+15] u16 (4 distinct)
    uint8_t  _pad9[4];    // body[+16..+19] zero
    uint8_t  field10[12]; // body[+20..+31] 12B (22 distinct)
    uint8_t  _pad11[2];   // body[+32..+33] zero
    uint32_t field12;     // body[+34..+37] u32 (3 distinct)
    uint8_t  _pad13[2];   // body[+38..+39] zero
    uint8_t  field14;     // body[+40] u8 (2 distinct)
    uint8_t  _pad15;      // body[+41] zero
    uint8_t  field16;     // body[+42] u8 (2 distinct)
    uint8_t  _pad17[4];   // body[+43..+46] zero
    uint8_t  field18;     // body[+47] u8 (2 distinct)
    uint8_t  _pad19[4];   // body[+48..+51] zero
    uint16_t field20;     // body[+52..+53] u16 (2 distinct)
    uint8_t  _pad21[2];   // body[+54..+55] zero
    uint8_t  field22;     // body[+56] u8 (2 distinct)
    uint8_t  _pad23[32];  // body[+57..+88] zero
    uint8_t  field24[7];  // body[+89..+95] 7B (5 distinct)
};

static_assert(sizeof(EventUpdateBody) == 96, "EventUpdateBody size mismatch");

// 0x012f (opcode 303) - sub_size=72B body=48B samples=44
struct ActorWorkUpdateBody
{
    uint16_t field0;    // body[+0..+1] u16 (30 distinct)
    uint8_t  _const1;   // body[+2] = 0xe0
    uint8_t  _const2;   // body[+3] = 0x50
    uint8_t  _pad3[4];  // body[+4..+7] zero
    uint8_t  _const4;   // body[+8] = 0x41
    uint8_t  _const5;   // body[+9] = 0x29
    uint8_t  _const6;   // body[+10] = 0x9b
    uint8_t  _const7;   // body[+11] = 0x02
    uint8_t  _pad8[32]; // body[+12..+43] zero
    uint32_t field9;    // body[+44..+47] u32 (6 distinct)
};

static_assert(sizeof(ActorWorkUpdateBody) == 48, "ActorWorkUpdateBody size mismatch");

// 0x0133 (opcode 307) - sub_size=72B body=48B samples=36
struct GroupWorkUpdateBody
{
    uint8_t  field0[3]; // body[+0..+2] 3B (29 distinct)
    uint8_t  _const1;   // body[+3] = 0x50
    uint8_t  _pad2[4];  // body[+4..+7] zero
    uint8_t  field3[3]; // body[+8..+10] 3B (22 distinct)
    uint8_t  _pad4[3];  // body[+11..+13] zero
    uint16_t field5;    // body[+14..+15] u16 (3 distinct)
    uint8_t  _pad6[32]; // body[+16..+47] zero
};

static_assert(sizeof(GroupWorkUpdateBody) == 48, "GroupWorkUpdateBody size mismatch");

// 0x01cf (opcode 463) - sub_size=40B body=16B samples=2
struct _0x01CFBody
{
    uint8_t field0[3]; // body[+0..+2] 3B (2 distinct)
    uint8_t _const1;   // body[+3] = 0x50
    uint8_t _pad2[8];  // body[+4..+11] zero
    uint8_t _const3;   // body[+12] = 0x7e
    uint8_t _const4;   // body[+13] = 0xea
    uint8_t _const5;   // body[+14] = 0x18
    uint8_t _pad6;     // body[+15] zero
};

static_assert(sizeof(_0x01CFBody) == 16, "_0x01CFBody size mismatch");

// 0x01dd (opcode 477) - sub_size=296B body=272B samples=1
struct _0x01DDBody
{
    uint8_t _const0;     // body[+0] = 0xea
    uint8_t _const1;     // body[+1] = 0xe8
    uint8_t _const2;     // body[+2] = 0xe0
    uint8_t _const3;     // body[+3] = 0x50
    uint8_t _pad4[8];    // body[+4..+11] zero
    uint8_t _const5;     // body[+12] = 0x03
    uint8_t _pad6[3];    // body[+13..+15] zero
    uint8_t _const7;     // body[+16] = 0x02
    uint8_t _const8;     // body[+17] = 0x01
    uint8_t _const9;     // body[+18] = 0x32
    uint8_t _pad10[253]; // body[+19..+271] zero
};

static_assert(sizeof(_0x01DDBody) == 272, "_0x01DDBody size mismatch");

} // namespace serverbound
} // namespace bahamut::opcodes::map

#pragma pack(pop)
